micronaut:
  application:
    name: github-team-dashboard
  router:
    static-resources:
      webjars:
        enabled: true
        paths: classpath:META-INF/resources/webjars
        mapping: /webjars/**

github:
  organization: ${GITHUB_ORGANIZATION}
  team: ${GITHUB_TEAM}
  token: ${GITHUB_TOKEN}
  userAgent: github-team-dashboard